import json
import os
from pygame import Color


def load_json_file(filename):
    with open(filename, "r", encoding="UTF-8") as file:
        return json.load(file)


constants = load_json_file(os.path.join("assets", "constants.json"))
assets = load_json_file(os.path.join("assets", "assets.json"))

WINDOW_WIDTH: int = constants["WINDOW_WIDTH"]
WINDOW_HEIGHT: int = constants["WINDOW_HEIGHT"]
CARD_WIDTH: int = constants["CARD_WIDTH"]
CARD_HEIGHT: int = constants["CARD_HEIGHT"]
MAX_HAND_CARD_AMOUNT: int = constants["MAX_HAND_CARD_AMOUNT"]
CARD_MASK_ALPHA: int = constants["CARD_MASK_ALPHA"]
GAME_TITLE: str = constants["GAME_TITLE"]
DEFAULT_FONT_SIZE: int = constants["DEFAULT_FONT_SIZE"]
DEFAULT_TEXT_BTN_WIDTH: int = constants["DEFAULT_TEXT_BTN_WIDTH"]
DEFAULT_TEXT_BTN_HEIGHT: int = constants["DEFAULT_TEXT_BTN_HEIGHT"]
DEFAULT_ROUND_BTN_WIDTH: int = constants["DEFAULT_ROUND_BTN_WIDTH"]
DEFAULT_ROUND_BTN_HEIGHT: int = constants["DEFAULT_ROUND_BTN_HEIGHT"]
CHANGE_BGM_LATE: int = constants["CHANGE_BGM_LATE"]


class File:
    FOLDER_ASSET: str = assets["FOLDER_ASSET"]
    FOLDER_IMAGE: str = assets["FOLDER_IMAGE"]
    FOLDER_AUDIO: str = assets["FOLDER_AUDIO"]
    FOLDER_FONT: str = assets["FOLDER_FONT"]
    FOLDER_LOCAL_DATA: str = assets["FOLDER_LOCAL_DATA"]
    AUDIO_SELECT_CARD: str = assets["AUDIO_SELECT_CARD"]
    AUDIO_CARD_ATTACK: str = assets["AUDIO_CARD_ATTACK"]

    AUDIO_KSP_7414: str = assets["AUDIO_KSP_7414"]
    AUDIO_CYGNUS_WTF: str = assets["AUDIO_CYGNUS_WTF"]
    AUDIO_OUMUA_ANGRY: str = assets["AUDIO_OUMUA_ANGRY"]
    AUDIO_D2_LOVEU: str = assets["AUDIO_D2_LOVEU"]
    AUDIO_NEMO_CHARM: str = assets["AUDIO_NEMO_CHARM"]
    AUDIO_SPRINGFISH_DEADGE: str = assets["AUDIO_SPRINGFISH_DEADGE"]
    AUDIO_LUTRA_ANGRY: str = assets["AUDIO_LUTRA_ANGRY"]
    AUDIO_15_SHOOT: str = assets["AUDIO_15_SHOOT"]
    AUDIO_OBEAR_SHUTUP: str = assets["AUDIO_OBEAR_SHUTUP"]
    AUDIO_RESCUTE_NONEEDPOOP: str = assets["AUDIO_RESCUTE_NONEEDPOOP"]
    AUDIO_SEKI_5MA: str = assets["AUDIO_SEKI_5MA"]
    AUDIO_YANHUA_BABY: str = assets["AUDIO_YANHUA_BABY"]
    AUDIO_QTTSIX_LOVEYANHUA: str = assets["AUDIO_QTTSIX_LOVEYANHUA"]
    AUDIO_QTTSIXYANHUA_LOVERS: str = assets["AUDIO_QTTSIXYANHUA_LOVERS"]
    AUDIO_KSEKI_LOVEEACHOTHER: str = assets["AUDIO_KSEKI_LOVEEACHOTHER"]
    AUDIO_APEX_POPHEALTH: str = assets["AUDIO_APEX_POPHEALTH"]
    AUDIO_APEX_POPBAT: str = assets["AUDIO_APEX_POPBAT"]
    AUDIO_APEX_POPPHINIX: str = assets["AUDIO_APEX_POPPHINIX"]
    AUDIO_JONGIE_BOMBOMBITCH: str = assets["AUDIO_JONGIE_BOMBOMBITCH"]
    AUDIO_REN_BEIDOL: str = assets["AUDIO_REN_BEIDOL"]
    AUDIO_RESTIA_PAYTHEPRICE: str = assets["AUDIO_RESTIA_PAYTHEPRICE"]
    AUDIO_MARGARET_UNBUTTON: str = assets["AUDIO_MARGARET_UNBUTTON"]
    AUDIO_LINGLAN_DARKCUISINE: str = assets["AUDIO_LINGLAN_DARKCUISINE"]
    AUDIO_LINGLAN_WOOFWOOF: str = assets["AUDIO_LINGLAN_WOOFWOOF"]
    AUDIO_RC_YOUAREGOOD: str = assets["AUDIO_RC_YOUAREGOOD"]
    AUDIO_RC_WATERMELONMILK: str = assets["AUDIO_RC_WATERMELONMILK"]
    AUDIO_RSD2_RE45YEAH: str = assets["AUDIO_RSD2_RE45YEAH"]
    AUDIO_MARGARET_AHHHHH: str = assets["AUDIO_MARGARET_AHHHHH"]
    AUDIO_EMOTIONAL_DAMAGE: str = assets["AUDIO_EMOTIONAL_DAMAGE"]

    AUDIO_WINING: str = assets["AUDIO_WINING"]
    AUDIO_LOSING: str = assets["AUDIO_LOSING"]
    AUDIO_BTN_DOWN: str = assets["AUDIO_BTN_DOWN"]
    AUDIO_BTN_UP: str = assets["AUDIO_BTN_UP"]
    AUDIO_DRAW_CARD_BEGIN: str = assets["AUDIO_DRAW_CARD_BEGIN"]
    AUDIO_DRAW_CARD: str = assets["AUDIO_DRAW_CARD"]

    IMAGE_BG_MENU: str = assets["IMAGE_BG_MENU"]
    IMAGE_BG_BATTLE_FIELD: str = assets["IMAGE_BG_BATTLE_FIELD"]
    IMAGE_BTN_TEXT_UP: str = assets["IMAGE_BTN_TEXT_UP"]
    IMAGE_BTN_TEXT_DOWN: str = assets["IMAGE_BTN_TEXT_DOWN"]
    IMAGE_BTN_TEXT_UP_WIDTH2X: str = assets["IMAGE_BTN_TEXT_UP_WIDTH2X"]
    IMAGE_BTN_TEXT_DOWN_WIDTH2X: str = assets["IMAGE_BTN_TEXT_DOWN_WIDTH2X"]
    IMAGE_BTN_LEFT_UP: str = assets["IMAGE_BTN_LEFT_UP"]
    IMAGE_BTN_LEFT_DOWN: str = assets["IMAGE_BTN_LEFT_DOWN"]
    IMAGE_BTN_RIGHT_UP: str = assets["IMAGE_BTN_RIGHT_UP"]
    IMAGE_BTN_RIGHT_DOWN: str = assets["IMAGE_BTN_RIGHT_DOWN"]
    IMAGE_BATTLE_CARD_ATTACK_BG: str = assets["IMAGE_BATTLE_CARD_ATTACK_BG"]
    IMAGE_PLAYER_HP: str = assets["IMAGE_PLAYER_HP"]
    IMAGE_PLAYER_SHIELD: str = assets["IMAGE_PLAYER_SHIELD"]
    IMAGE_PLAYER_HP_BG: str = assets["IMAGE_PLAYER_HP_BG"]
    IMAGE_PLAYER_SHIELD_BG: str = assets["IMAGE_PLAYER_SHIELD_BG"]
    IMAGE_WIN_SIGN: str = assets["IMAGE_WIN_SIGN"]
    IMAGE_LOSE_SIGN: str = assets["IMAGE_LOSE_SIGN"]
    IMAGE_ROUND_START_SIGN: str = assets["IMAGE_ROUND_START_SIGN"]
    IMAGE_ROUND_END_SIGN: str = assets["IMAGE_ROUND_END_SIGN"]
    IMAGE_EFFECT_VOMIT_SUGAR: str = assets["IMAGE_EFFECT_VOMIT_SUGAR"]
    IMAGE_EFFECT_FULL_SUGAR: str = assets["IMAGE_EFFECT_FULL_SUGAR"]
    IMAGE_CARD_DISCARD_MASK: str = assets["IMAGE_CARD_DISCARD_MASK"]
    IMAGE_GOOD_AT_TAKE_OFF_SHIRT: str = assets["IMAGE_GOOD_AT_TAKE_OFF_SHIRT"]
    IMAGE_APEX_PREDATOR: str = assets["IMAGE_APEX_PREDATOR"]
    IMAGE_CARD_LOCK: str = assets["IMAGE_CARD_LOCK"]
    IMAGE_NOT_FINISH_SIGN: str = assets["IMAGE_NOT_FINISH_SIGN"]
    IMAGE_MODE_DETAIL_EASY: str = assets["IMAGE_MODE_DETAIL_EASY"]
    IMAGE_MODE_DETAIL_NORMAL: str = assets["IMAGE_MODE_DETAIL_NORMAL"]
    IMAGE_MODE_DETAIL_HARD: str = assets["IMAGE_MODE_DETAIL_HARD"]
    IMAGE_MODE_DETAIL_SUPER_HARD: str = assets["IMAGE_MODE_DETAIL_SUPER_HARD"]
    IMAGE_MODE_DETAIL_ASIAN: str = assets["IMAGE_MODE_DETAIL_ASIAN"]
    IMAGE_MODE_DETAIL_RANDOM: str = assets["IMAGE_MODE_DETAIL_RANDOM"]
    IMAGE_MODE_DETAIL_CREATE_CONNECT: str = assets["IMAGE_MODE_DETAIL_CREATE_CONNECT"]
    IMAGE_MODE_DETAIL_JOIN_CONNECT: str = assets["IMAGE_MODE_DETAIL_JOIN_CONNECT"]

    IMAGE_ICON: str = assets["IMAGE_ICON"]
    IMAGE_GAME_RULE_0: str = assets["IMAGE_GAME_RULE_0"]
    IMAGE_GAME_RULE_1: str = assets["IMAGE_GAME_RULE_1"]
    IMAGE_GAME_RULE_2: str = assets["IMAGE_GAME_RULE_2"]
    IMAGE_GAME_RULE_3: str = assets["IMAGE_GAME_RULE_3"]
    IMAGE_GAME_RULE_4: str = assets["IMAGE_GAME_RULE_4"]
    IMAGE_DECLARATION_ZH: str = assets["IMAGE_DECLARATION_ZH"]
    IMAGE_DECLARATION_EN: str = assets["IMAGE_DECLARATION_EN"]
    IMAGE_ABOUT_GAME_00: str = assets["IMAGE_ABOUT_GAME_00"]
    IMAGE_ABOUT_GAME_01: str = assets["IMAGE_ABOUT_GAME_01"]
    IMAGE_ABOUT_GAME_02: str = assets["IMAGE_ABOUT_GAME_02"]
    IMAGE_ABOUT_GAME_03: str = assets["IMAGE_ABOUT_GAME_03"]
    IMAGE_GACHA_POOL_BASEPLAYER: str = assets["IMAGE_GACHA_POOL_BASEPLAYER"]
    IMAGE_GACHA_POOL_DETAIL_BASEPLAYER: str = assets["IMAGE_GACHA_POOL_DETAIL_BASEPLAYER"]

    FONT_DEFAULT: str = assets["FONT_TSTC"]


COLOR_BLACK: Color = Color(0, 0, 0)
COLOR_GRAY: Color = Color(128, 128, 128)
COLOR_WHITE: Color = Color(255, 255, 255)
DEFAULT_FONT_COLOR: Color = COLOR_BLACK
